# Generated by Django 5.0 on 2024-04-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('International_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='User.user')),
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='User.user')),
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Number_of_children', models.CharField(max_length=50)),
            ],
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='User.user')),
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Education_level', models.CharField(max_length=50)),
                ('Debt_status', models.CharField(max_length=50)),
            ],
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='User.user')),
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Code_vezarat_olom', models.CharField(max_length=50)),
                ('Work_experience', models.BooleanField(default=False)),
                ('Education', models.CharField(max_length=50)),
            ],
            bases=('User.user', models.Model),
        ),
    ]
